# docker-compose.yml

version: "3.8"

services:
  web:
    build: .
    volumes:
      - .:/past_questions_bot
    ports:
      - 8008:8000
    depends_on:
      - redis

  redis:
    image: redis:latest
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  litestream:
    image: litestream/litestream:0.3.13
    volumes:
      - ./past_questions_bot.db:/past_questions_bot.db 
      - ./litestream.yml:/etc/litestream.yml
    command: ["replicate", "-config", "/etc/litestream.yml"]
    environment:
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_REGION=${S3_REGION}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
