# docker-compose.yml

version: '3.8'

services:
  web:
    build: 
      context: . 
      dockerfile: Dockerfile.prod
    volumes:
      - .:/past_questions_bot
    ports:
      - 8009:80
    depends_on:
      - db
    env_file:
      - env.prod
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}\
    env_file:
      - env.prod

volumes:
  postgres_data_prod: