FROM python:3.11

WORKDIR /code

ENV PYTHONUNBUFFERED=1 \
    POETRY_HOME="/code/poetry" \
    POETRY_VERSION=1.2.2
    

ENV PATH="$POETRY_HOME/bin:$PATH"

RUN pip install --no-cache-dir --upgrade "poetry==${POETRY_VERSION}"

COPY poetry.lock pyproject.toml /code/

RUN poetry config virtualenvs.create false

RUN poetry install

COPY . /code/

CMD ["python", "src/main.py"]