name: Build and Test

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format code with black
        run: |
          pip install black
          black .
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "Format code with black"
          add: "."
          branch: ${{ github.ref }}

  build:
    name: Build and Test
    runs-on: ubuntu-latest

    env:
      USER_NAME: "10900000"
      PASSWORD: "0000"
      URL: "https://balme.ug.edu.gh/past.exampapers/index.php?p=member"
      TOKEN: "TOKEN FROM BOTFATHER"
      DEVELOPER_CHAT_ID: "TELEGRAM ID TO RECEIVE ERROR MESSAGES"
      PORT: "8443"
      BUCKET_NAME: "bucket_name"
      REGION: "us-east-1"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      id: dependency
      run: |
        python -m pip install --upgrade pip
        pip install poetry pytest
        poetry config virtualenvs.create false
        poetry install
        
    - name: Run Unit and Integration Tests
      run: |
        python -m unit -v
        python -m integration -v 